### ISSUE TITLE
Mechanism to exclude specific modules/required-assets

### ISSUE THREAD

**Issue by dizzystuff** [xini/silverstripe-prefix-requirements#1]
The css of some modules contain relative references to fonts, images, and/or similar assets.

When this module does its work and produces a hashed file and places it in/serves it from /assets/_combinedfiles, the references to those assets are broken (they remain relative to the original css file within _resources/vendor/module/etc).

Ideally, those modules would have improved references? But, it would also be helpful to be able to define which specific resources and/or modules should be excluded from the function of this module.

Replicable by installing [silverstripe-debugbar](https://github.com/lekoala/silverstripe-debugbar/) alongside this one. All icons are not served as the fonts break with 404s.

Noting this here with the hope of coming back to figure it out with a PR some time :)

**Comment by xini** [comment]
Yes, I have come across this myself. I usually block those requirements from loading and build my own bundle with trumps for overwritten, absolute references to those fonts/images. 

Maybe there is a better way of doing these hashes, leaving the files where they are and using a custom route and controller to add the hash on the fly? Not sure...

**Comment by dizzystuff** [comment]
Resolved in 2.2.0, thanks!
